services:
  mysql:
    image: mysql:8.0
    container_name: mysql_project
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_management
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: project_api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_management
      DB_PORT: 3306
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
